### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by johnny14789** [lucko515/image-search-engine#5]
can u please tell me what this errors are :+1: 2021-06-27 23:00:09.416600: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-06-27 23:00:09.416646: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/nomnom/image-search-engine/app.py", line 25, in <module>
    model = ImageSearchModel(learning_rate=cfg.LEARNING_RATE, image_size=cfg.IMAGE_SIZE, number_of_classes=cfg.NUMBER_OF_CLASSES)
  File "/home/nomnom/image-search-engine/model.py", line 20, in __init__
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

**Comment by johnny14789** [comment]
Can u please make a short video on how to install and setup .very eager to learn this project!!1Thank you
